"""Assemble per-lesion tool outputs into a structured StudyReport.

Abnormality-first: list detected lesions, then describe each. Every numeric field is
wrapped as `Sourced(value, source=<tool_call_id>)` so the traceability guard can verify
no number entered the report without a tool-call provenance. The narrative text is
generated by the LLM agent; this module builds/validates the machine-readable structure.
"""

from __future__ import annotations

from oncoct.report.schema import LesionReport, RecistCategory, Sourced, StudyReport


def build_study_report(study_uid: str, lesion_records: list[dict]) -> StudyReport:
    """Build a validated StudyReport from tool outputs.

    Each record in ``lesion_records`` must include the measurement values AND the
    tool_call id that produced them (``*_source`` keys). RECIST target/non-target uses
    the RECIST 1.1 rule (measurable target lesion: long axis >= 10mm).
    """
    findings: list[LesionReport] = []
    sum_diam = 0.0
    sum_sources: list[str] = []

    for r in lesion_records:
        long_axis = r["long_axis_mm"]
        category = (
            RecistCategory.TARGET if long_axis >= 10.0 else RecistCategory.NON_TARGET
        )
        if category is RecistCategory.TARGET:
            sum_diam += long_axis
            sum_sources.append(r["long_axis_source"])

        findings.append(
            LesionReport(
                lesion_id=r["lesion_id"],
                organ=r["organ"],
                lobe_or_segment=r.get("lobe_or_segment"),
                long_axis_mm=Sourced(value=long_axis, source=r["long_axis_source"]),
                short_axis_mm=Sourced(value=r["short_axis_mm"], source=r["short_axis_source"]),
                volume_mm3=Sourced(value=r["volume_mm3"], source=r["volume_source"]),
                malignancy_score=Sourced(value=r["malignancy_score"], source=r["malignancy_source"]),
                malignancy_confidence=r["malignancy_confidence"],
                recist_category=category,
                detector_score=r["detector_score"],
                quality_flags=r.get("quality_flags", []),
            )
        )

    recist_sum = (
        Sourced(value=round(sum_diam, 2), source=";".join(sum_sources)) if sum_sources else None
    )
    return StudyReport(
        study_uid=study_uid,
        findings=findings,
        impression="",  # filled by the LLM narration step
        recist_sum_of_diameters_mm=recist_sum,
    )
