"""Assemble per-lesion tool outputs into a structured StudyReport.

Abnormality-first: list detected lesions, then describe each. Every numeric field is
wrapped as `Sourced(value, source=<tool_call_id>)` so the traceability guard can verify
no number entered the report without a tool-call provenance. The narrative text is
generated by the LLM agent; this module builds/validates the machine-readable structure.

Target-lesion selection follows RECIST 1.1 rather than "everything over 10mm":
a lesion must be measurable, must not carry a quality flag, and the selected set is
capped per organ and in total. See `select_recist_targets`.
"""

from __future__ import annotations

from oncoct.report.schema import LesionReport, RecistCategory, Sourced, StudyReport

# RECIST 1.1 target-lesion rules.
MIN_MEASURABLE_LONG_AXIS_MM = 10.0
MAX_TARGETS_PER_ORGAN = 2
MAX_TARGET_LESIONS = 5


def select_recist_targets(lesion_records: list[dict]) -> dict[str, str | None]:
    """Choose the RECIST 1.1 target lesions.

    Returns lesion_id -> None if it is a target, or a string saying why it is not.
    Lesions under the measurability threshold are simply non-target and get no reason;
    the reason exists to explain a lesion that was big enough but still not selected.

    Three rules, all of which the naive "long_axis >= 10mm" test gets wrong:

    1. **A flagged lesion cannot be a target.** RECIST targets are the lesions whose
       measurement is tracked over time, so a lesion the pipeline itself marked as
       unreliable (mask ran away, outside the organ, ambiguous attribution) must not
       carry the headline number. Without this the sum of diameters can rest entirely
       on the one finding the report is simultaneously warning about.
    2. **At most two target lesions per organ.**
    3. **At most five target lesions in total.**

    Selection is largest-first by long axis, which is what RECIST asks for, with the
    lesion id as a tie-break so the choice is deterministic.
    """
    eligible, verdict = [], {}

    for r in lesion_records:
        lesion_id = r["lesion_id"]
        if r["long_axis_mm"] < MIN_MEASURABLE_LONG_AXIS_MM:
            verdict[lesion_id] = None  # not measurable; plain non-target, no explanation owed
        elif r.get("quality_flags"):
            verdict[lesion_id] = (
                f"carries quality flag(s) {', '.join(r['quality_flags'])}, "
                "so its measurement is not reliable enough to track"
            )
        else:
            eligible.append(r)

    eligible.sort(key=lambda r: (-r["long_axis_mm"], r["lesion_id"]))

    per_organ: dict[str, int] = {}
    n_selected = 0
    for r in eligible:
        organ = r.get("organ") or "unknown"
        if n_selected >= MAX_TARGET_LESIONS:
            verdict[r["lesion_id"]] = (
                f"study already has the maximum of {MAX_TARGET_LESIONS} target lesions"
            )
        elif per_organ.get(organ, 0) >= MAX_TARGETS_PER_ORGAN:
            verdict[r["lesion_id"]] = (
                f"{organ} already has the maximum of {MAX_TARGETS_PER_ORGAN} target lesions"
            )
        else:
            per_organ[organ] = per_organ.get(organ, 0) + 1
            n_selected += 1
            verdict[r["lesion_id"]] = None  # selected

    return verdict


def build_study_report(study_uid: str, lesion_records: list[dict]) -> StudyReport:
    """Build a validated StudyReport from tool outputs.

    Each record in ``lesion_records`` must include the measurement values AND the
    tool_call id that produced them (``*_source`` keys). Target lesions are chosen by
    :func:`select_recist_targets`, and only those contribute to the sum of diameters.
    """
    findings: list[LesionReport] = []
    sum_diam = 0.0
    sum_sources: list[str] = []

    exclusion = select_recist_targets(lesion_records)
    measurable = {
        r["lesion_id"] for r in lesion_records if r["long_axis_mm"] >= MIN_MEASURABLE_LONG_AXIS_MM
    }

    for r in lesion_records:
        lesion_id = r["lesion_id"]
        long_axis = r["long_axis_mm"]
        reason = exclusion.get(lesion_id)
        is_target = lesion_id in measurable and reason is None
        category = RecistCategory.TARGET if is_target else RecistCategory.NON_TARGET
        if is_target:
            sum_diam += long_axis
            sum_sources.append(r["long_axis_source"])

        findings.append(
            LesionReport(
                lesion_id=lesion_id,
                organ=r["organ"],
                lobe_or_segment=r.get("lobe_or_segment"),
                long_axis_mm=Sourced(value=long_axis, source=r["long_axis_source"]),
                short_axis_mm=Sourced(value=r["short_axis_mm"], source=r["short_axis_source"]),
                volume_mm3=Sourced(value=r["volume_mm3"], source=r["volume_source"]),
                malignancy_score=Sourced(
                    value=r["malignancy_score"], source=r["malignancy_source"]
                ),
                malignancy_confidence=r["malignancy_confidence"],
                recist_category=category,
                detector_score=r["detector_score"],
                quality_flags=r.get("quality_flags", []),
                recist_exclusion_reason=reason,
            )
        )

    recist_sum = (
        Sourced(value=round(sum_diam, 2), source=";".join(sum_sources)) if sum_sources else None
    )
    return StudyReport(
        study_uid=study_uid,
        findings=findings,
        impression="",  # filled by the LLM narration step
        recist_sum_of_diameters_mm=recist_sum,
    )
